Create the XOR Dataset

In [1]:
import numpy as np

# XOR input data
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
], dtype=np.float32)

# XOR output
y = np.array([
    [0],
    [1],
    [1],
    [0]
], dtype=np.float32)

print("Input X:")
print(X)

print("\nOutput y:")
print(y)

Input X:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]

Output y:
[[0.]
 [1.]
 [1.]
 [0.]]


Build the MLP using Keras

In [3]:
%pip install tensorflow

   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
    --------------------------------------- 6.6/351.2 MB 37.8 MB/s eta 0:00:10
   - -------------------------------------- 11.5/351.2 MB 28.5 MB/s eta 0:00:12
   - -------------------------------------- 16.5/351.2 MB 26.6 MB/s eta 0:00:13
   -- ------------------------------------- 20.7/351.2 MB 24.7 MB/s eta 0:00:14
   -- ------------------------------------- 24.9/351.2 MB 24.0 MB/s eta 0:00:14
   --- ------------------------------------ 29.4/351.2 MB 23.4 MB/s eta 0:00:14
   --- ------------------------------------ 34.1/351.2 MB 23.0 MB/s eta 0:00:14
   ---- ----------------------------------- 39.1/351.2 MB 23.1 MB/s eta 0:00:14
   ---- ----------------------------------- 43.8/351.2 MB 23.1 MB/s eta 0:00:14
   ----- ---------------------------------- 49.0/351.2 MB 23.2 MB/s eta 0:00:14
   ------ --------------------------------- 54.0/351.2 MB 23.2 MB/s eta 0:00:13
   ------ --------------------------------- 56.9/3

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.42.1 requires protobuf<6,>=3.20, but you have protobuf 7.35.1 which is incompatible.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tens

In [4]:
import tensorflow as tf

print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.21.0


In [5]:
from tensorflow import keras
from tensorflow.keras import layers

# Create the MLP model
model = keras.Sequential([
    layers.Input(shape=(2,)),
    layers.Dense(4, activation='tanh'),
    layers.Dense(1, activation='sigmoid')
])

# Display model architecture
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 4)              │            12 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 17 (68.00 B)

 Trainable params: 17 (68.00 B)

 Non-trainable params: 0 (0.00 B)

Compile the Keras model

In [6]:
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.01),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

print("Model compiled successfully!")

Model compiled successfully!


Train the Keras MLP

In [7]:
history = model.fit(
    X,
    y,
    epochs=1000,
    verbose=0
)

print("Model training completed!")

Model training completed!


Predict the XOR outputs

In [8]:
predictions = model.predict(X, verbose=0)

print("Predicted probabilities:")
print(predictions)

print("\nPredicted classes:")
print((predictions >= 0.5).astype(int))

print("\nActual outputs:")
print(y.astype(int))

Predicted probabilities:
[[4.3955704e-04]
 [9.9448729e-01]
 [9.9174470e-01]
 [1.1866627e-02]]

Predicted classes:
[[0]
 [1]
 [1]
 [0]]

Actual outputs:
[[0]
 [1]
 [1]
 [0]]


Calculate Accuracy

In [9]:
from sklearn.metrics import accuracy_score

predicted_classes = (predictions >= 0.5).astype(int)

accuracy = accuracy_score(y, predicted_classes)

print("Final Accuracy:", accuracy)
print("Accuracy Percentage:", accuracy * 100, "%")

Final Accuracy: 1.0
Accuracy Percentage: 100.0 %


Build the MLP using PyTorch

In [10]:
import torch

print("PyTorch version:", torch.__version__)

PyTorch version: 2.6.0+cpu


In [11]:
import torch
import torch.nn as nn
import torch.optim as optim

# Convert XOR data to PyTorch tensors
X_torch = torch.tensor(X, dtype=torch.float32)
y_torch = torch.tensor(y, dtype=torch.float32)

# Define the MLP
class XOR_MLP(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.network = nn.Sequential(
            nn.Linear(2, 4),
            nn.Tanh(),
            nn.Linear(4, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.network(x)

# Create the model
torch_model = XOR_MLP()

print(torch_model)

XOR_MLP(
  (network): Sequential(
    (0): Linear(in_features=2, out_features=4, bias=True)
    (1): Tanh()
    (2): Linear(in_features=4, out_features=1, bias=True)
    (3): Sigmoid()
  )
)


Define Loss Function and Optimizer

In [12]:
# Binary Cross-Entropy loss
criterion = nn.BCELoss()

# Adam optimizer with learning rate 0.01
optimizer = optim.Adam(
    torch_model.parameters(),
    lr=0.01
)

print("Loss function and optimizer defined successfully!")

Loss function and optimizer defined successfully!


Train the PyTorch MLP

In [13]:
epochs = 1000

for epoch in range(epochs):
    # Forward pass
    outputs = torch_model(X_torch)

    # Calculate loss
    loss = criterion(outputs, y_torch)

    # Clear previous gradients
    optimizer.zero_grad()

    # Backpropagation
    loss.backward()

    # Update weights
    optimizer.step()

print("PyTorch model training completed!")

PyTorch model training completed!


PyTorch Predictions

In [14]:
# Make predictions
with torch.no_grad():
    torch_predictions = torch_model(X_torch)

# Convert probabilities to classes
torch_classes = (torch_predictions >= 0.5).int()

print("Predicted probabilities:")
print(torch_predictions)

print("\nPredicted classes:")
print(torch_classes)

print("\nActual outputs:")
print(y_torch.int())

Predicted probabilities:
tensor([[2.9455e-04],
        [9.9269e-01],
        [9.9424e-01],
        [1.1903e-02]])

Predicted classes:
tensor([[0],
        [1],
        [1],
        [0]], dtype=torch.int32)

Actual outputs:
tensor([[0],
        [1],
        [1],
        [0]], dtype=torch.int32)


In [15]:
correct = (torch_classes == y_torch.int()).sum().item()
total = y_torch.size(0)

torch_accuracy = correct / total

print("PyTorch Accuracy:", torch_accuracy)
print("Accuracy Percentage:", torch_accuracy * 100, "%")

PyTorch Accuracy: 1.0
Accuracy Percentage: 100.0 %


TensorFlow Low-Level API

In [16]:
import tensorflow as tf

# Create TensorFlow tensors
X_tf = tf.constant(X, dtype=tf.float32)
y_tf = tf.constant(y, dtype=tf.float32)

# Initialize weights and biases
W1 = tf.Variable(tf.random.normal([2, 4]))
b1 = tf.Variable(tf.zeros([4]))

W2 = tf.Variable(tf.random.normal([4, 1]))
b2 = tf.Variable(tf.zeros([1]))

print("TensorFlow low-level model initialized successfully!")

TensorFlow low-level model initialized successfully!


Define Forward Pass and Optimizer

In [17]:
# Adam optimizer
optimizer_tf = tf.optimizers.Adam(learning_rate=0.01)

# Binary Cross-Entropy loss
loss_fn = tf.keras.losses.BinaryCrossentropy()

def forward_pass(X):
    # Hidden layer
    hidden = tf.tanh(tf.matmul(X, W1) + b1)

    # Output layer
    output = tf.sigmoid(tf.matmul(hidden, W2) + b2)

    return output

print("Forward pass and optimizer defined successfully!")

Forward pass and optimizer defined successfully!


Train the TensorFlow Low-Level Model

In [18]:
epochs = 1000

for epoch in range(epochs):
    with tf.GradientTape() as tape:
        predictions_tf = forward_pass(X_tf)
        loss = loss_fn(y_tf, predictions_tf)

    gradients = tape.gradient(
        loss,
        [W1, b1, W2, b2]
    )

    optimizer_tf.apply_gradients(
        zip(gradients, [W1, b1, W2, b2])
    )

print("TensorFlow low-level model training completed!")
print("Final Loss:", float(loss))

TensorFlow low-level model training completed!
Final Loss: 0.00635179877281189


Make TensorFlow Predictions

In [19]:
# Generate predictions
predictions_tf = forward_pass(X_tf)

# Convert probabilities to binary classes
classes_tf = tf.cast(predictions_tf >= 0.5, tf.int32)

print("Predicted probabilities:")
print(predictions_tf.numpy())

print("\nPredicted classes:")
print(classes_tf.numpy())

print("\nActual outputs:")
print(y_tf.numpy().astype(int))

Predicted probabilities:
[[0.00105201]
 [0.9954331 ]
 [0.9908743 ]
 [0.01050883]]

Predicted classes:
[[0]
 [1]
 [1]
 [0]]

Actual outputs:
[[0]
 [1]
 [1]
 [0]]


In [20]:
correct_tf = tf.reduce_sum(
    tf.cast(classes_tf == tf.cast(y_tf, tf.int32), tf.int32)
)

total_tf = tf.size(y_tf)

tf_accuracy = float(correct_tf.numpy() / total_tf.numpy())

print("TensorFlow Low-Level Accuracy:", tf_accuracy)
print("Accuracy Percentage:", tf_accuracy * 100, "%")

TensorFlow Low-Level Accuracy: 1.0
Accuracy Percentage: 100.0 %


Experiment with Number of Neurons

In [21]:
from tensorflow import keras
from tensorflow.keras import layers

neurons_list = [2, 4, 8]

for neurons in neurons_list:
    test_model = keras.Sequential([
        layers.Input(shape=(2,)),
        layers.Dense(neurons, activation='tanh'),
        layers.Dense(1, activation='sigmoid')
    ])

    test_model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=0.01),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    test_model.fit(X, y, epochs=1000, verbose=0)

    loss, accuracy = test_model.evaluate(X, y, verbose=0)

    print(f"Neurons: {neurons} | Accuracy: {accuracy * 100:.2f}%")

Neurons: 2 | Accuracy: 100.00%
Neurons: 4 | Accuracy: 100.00%
Neurons: 8 | Accuracy: 100.00%


In [22]:
learning_rates = [0.001, 0.01, 0.1]

for lr in learning_rates:
    test_model = keras.Sequential([
        layers.Input(shape=(2,)),
        layers.Dense(4, activation='tanh'),
        layers.Dense(1, activation='sigmoid')
    ])

    test_model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=lr),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    test_model.fit(X, y, epochs=1000, verbose=0)

    loss, accuracy = test_model.evaluate(X, y, verbose=0)

    print(f"Learning Rate: {lr} | Accuracy: {accuracy * 100:.2f}% | Loss: {loss:.6f}")

Learning Rate: 0.001 | Accuracy: 100.00% | Loss: 0.291678
Learning Rate: 0.01 | Accuracy: 100.00% | Loss: 0.003848
Learning Rate: 0.1 | Accuracy: 100.00% | Loss: 0.000113


Experiment with Activation Function

In [23]:
activation_functions = ['tanh', 'relu']

for activation in activation_functions:
    test_model = keras.Sequential([
        layers.Input(shape=(2,)),
        layers.Dense(4, activation=activation),
        layers.Dense(1, activation='sigmoid')
    ])

    test_model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=0.01),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    test_model.fit(X, y, epochs=1000, verbose=0)

    loss, accuracy = test_model.evaluate(X, y, verbose=0)

    print(
        f"Activation: {activation} | "
        f"Accuracy: {accuracy * 100:.2f}% | "
        f"Loss: {loss:.6f}"
    )

Activation: tanh | Accuracy: 100.00% | Loss: 0.002203
Activation: relu | Accuracy: 25.00% | Loss: 0.693147


Experiment with Number of Epochs

In [24]:
epochs_list = [100, 500, 1000]

for epochs in epochs_list:
    test_model = keras.Sequential([
        layers.Input(shape=(2,)),
        layers.Dense(4, activation='tanh'),
        layers.Dense(1, activation='sigmoid')
    ])

    test_model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=0.01),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    test_model.fit(X, y, epochs=epochs, verbose=0)

    loss, accuracy = test_model.evaluate(X, y, verbose=0)

    print(
        f"Epochs: {epochs} | "
        f"Accuracy: {accuracy * 100:.2f}% | "
        f"Loss: {loss:.6f}"
    )

Epochs: 100 | Accuracy: 100.00% | Loss: 0.396759
Epochs: 500 | Accuracy: 100.00% | Loss: 0.012990
Epochs: 1000 | Accuracy: 100.00% | Loss: 0.002110
